# STS settings
Sts.Role: arn:aws:iam::429614120872:role/remoteAdmin
Stack.Name: "{{ 'intake-' + env }}"

# Application settings
Stack.Inputs.ApplicationKeyName: admin-shared-key
Stack.Inputs.ApplicationInstanceType: t2.micro
Stack.Inputs.ApplicationDesiredCount: 2
Stack.Inputs.ApplicationImageId: ami-bb75e3db
Stack.Inputs.ApplicationDockerImage: 429614120872.dkr.ecr.us-west-2.amazonaws.com/cwds/intake
Stack.Inputs.ApplicationDockerImageTag: latest
Stack.Inputs.Applicationload_balancer_port: 443
Stack.Inputs.ApplicationPort: 3000
Stack.Inputs.ApplicationSecretKey: AQECAHgohc0dbuzR1L3lEdEkDC96PMYUEV9nITogJU2vbocgQAAAAIswgYgGCSqGSIb3DQEHBqB7MHkCAQAwdAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAw62iH9NcNJO/4TB5oCARCARxj8nW4pb1lLJuwFwEjuV3GHv7RZNHMgTyFldE6IJnbcPn95+RAYb7Y9LGlKwLLKDw+HS2ChZDQhbzFMzjhSAZeHczsANpi9
Stack.Inputs.ApplicationApiUrl: https://dev-intake-api.ca.mycasebook.org/
Stack.Inputs.ApplicationAuthentication: "true"
Stack.Inputs.ApplicationAuthenticationUrl: http://perry.intake.cwds.tabordasolutions.net
Stack.Inputs.ApplicationHostname: dev-intake
Stack.Inputs.ApplicationDomain: ca.mycasebook.org

# Nginx settings
Stack.Inputs.NginxDockerImage: 429614120872.dkr.ecr.us-west-2.amazonaws.com/cwds/nginx
Stack.Inputs.NginxDockerImageTag: latest

# Load balancer settings
Stack.Inputs.ApplicationLoadBalancerCertificateArn: CaMycasebookOrgCertArn

# Log settings
Stack.Inputs.LogRetention: 30
# Add a global override to resources of the given type
AWS::Logs::LogGroup:
  DeletionPolicy: Delete
