# STS settings
sts_role_arn: arn:aws:iam::429614120872:role/remoteAdmin

# Application settings
config_application_keyname: admin-shared-key
config_application_instance_type: t2.micro
config_application_desired_count: 2
config_application_ami: ami-fa1da79a
config_application_image: 429614120872.dkr.ecr.us-west-2.amazonaws.com/cwds/intake
config_application_tag: latest
config_application_frontend_port: 443
config_application_port: 3000
config_application_secret_key_base: AQECAHgohc0dbuzR1L3lEdEkDC96PMYUEV9nITogJU2vbocgQAAAAIswgYgGCSqGSIb3DQEHBqB7MHkCAQAwdAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAw62iH9NcNJO/4TB5oCARCARxj8nW4pb1lLJuwFwEjuV3GHv7RZNHMgTyFldE6IJnbcPn95+RAYb7Y9LGlKwLLKDw+HS2ChZDQhbzFMzjhSAZeHczsANpi9

# Nginx settings
config_nginx_image: 429614120872.dkr.ecr.us-west-2.amazonaws.com/cwds/nginx
config_nginx_tag: latest

# Log settings
config_log_retention: 30
config_log_deletion_policy: Delete